spring:
    application:
        name: crud
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3360/database
        username: root
        password: password
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true